theme: jekyll-theme-slate
title: Welcome to PinballAdventure's Homepage
description: Weekly Updates will be placed here.
Week1: Cian- I spent most of my time in photoshop doing designs for different skins the player can acquire. Along with that im currently designing the tutorial background in my own test scene that i plan to merge into main as a basis for our game.
