theme: jekyll-theme-slate
title: Welcome to PinballAdventure's Homepage
description: Weekly Updates will be placed here.
Week1: Cian- I spent most of my time in photoshop doing designs for different skins the player can acquire. Along with that im currently designing the tutorial background in my own test scene that i plan to merge into main as a basis for our game.
Week2: Cian- Started creating menu and UI elements in png formats to add into unity later
Week3: Cian- Added in png elements into unity test level 
Week4: Cian- Designing test level area with basic mechanics for game
Week5: Cian- Started coding UI menu scenes
Week6: Cian- 
Week7: Cian- Started designing Menu look in photoshop
Week8: Cian- Finished designing Menu design
